### ISSUE TITLE
Bails after fresh install on 16.04

### ISSUE THREAD

**Issue by landmanbester** [ska-sa/meqtrees-cattery#101]
I recently installed owlcat and I think it resulted in my casacore getting upgraded which broke the usual way I simulate data. After purging both meqtrees and casacore I still get the same error viz.

Successful readonly open of default-locked table facet_centers.MS_p0: 25 columns, 0 rows
1.5Gb tdlc(Compile.py:157:import_tdl_module): exception importing TDL file: /usr/lib/python2.7/dist-packages/Cattery/Siamese/turbo-sim.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Timba/TDL/Compile.py", line 136, in import_tdl_module
    _tdlmod = imp.load_source(modname,filename,infile);
  File "/usr/lib/python2.7/dist-packages/Cattery/Siamese/turbo-sim.py", line 114, in <module>
    from Siamese.OMS import oms_pointing_errors
  File "/usr/lib/python2.7/dist-packages/Cattery/Siamese/OMS/oms_pointing_errors.py", line 62, in <module>
    _pe_errgen_l = ErrorGens.Selector("pointing in l",0,10,label="pe_l",unit=("arcsec",ARCSEC));
  File "/usr/lib/python2.7/dist-packages/Cattery/Siamese/OMS/ErrorGens.py", line 203, in __init__
    gen = genclass(name,nominal_value,typical_error,label=label,**kw);
  File "/usr/lib/python2.7/dist-packages/Cattery/Siamese/OMS/ErrorGens.py", line 154, in __init__
    Meow.Context.mssel.when_changed(self.set_ms);
  File "/usr/lib/python2.7/dist-packages/Cattery/Meow/MSUtils.py", line 703, in when_changed
    callback(self._msname);
  File "/usr/lib/python2.7/dist-packages/Cattery/Siamese/OMS/ErrorGens.py", line 158, in set_ms
    t0,t1 = min(times),max(times);
TypeError: 'NoneType' object is not iterable
Exception caught:
Traceback (most recent call last):
  File "/usr/bin/meqtree-pipeliner.py", line 147, in <module>
    module,ns,msg = Compile.compile_file(mqs,script,config=section);
  File "/usr/lib/python2.7/dist-packages/Timba/TDL/Compile.py", line 302, in compile_file
    (tdlmod,text) = import_tdl_module(filename,text=text,config=config);
  File "/usr/lib/python2.7/dist-packages/Timba/TDL/Compile.py", line 164, in import_tdl_module
    raise TDL.CumulativeError(*ns.GetErrors());
CumulativeError: 
 [  1] 'NoneType' object is not iterable
### Stopping the meqserver
1.5Gb meqserver(meqserver.py:288:stop_default_mqs): meqserver not exited yet, waiting another 10 seconds
### All your batch are not belong to us, returning with error code
Makefile:17: recipe for target 'fc' failed
make: *** [fc] Error 1

Any ideas?

**Comment by landmanbester** [comment]
No from KERN-3. Why have these packages been upgraded? Thought they were supposed to remain fixed at stable versions

**Comment by landmanbester** [comment]
landman-X3 :: MS_dir/ddfacet_test_data/WSCMS_MSMF_WB_TestSuite » dpkg -l | grep meqtrees
ii  libmeqtrees-timba0                            1.5.0-1kern4                                 amd64        implementing and solving arbitrary Measurement Equations
ii  meqtrees                                      1.5.3-1                                      amd64        Meta package that depends on all MeqTrees subprojects.
ii  meqtrees-timba                                1.5.0-1kern4                                 amd64        implementing and solving arbitrary Measurement Equations
ii  python-kittens                                1.3.3-1kern5                                 amd64        Collection of Python utility functions for purr, tigger, meqtrees and others
ii  python-meqtrees-cattery                       1.5.3-1                                      amd64        Frameworks for simulation and calibration of radio interferometers
ii  python-meqtrees-timba                         1.5.0-1kern4                                 amd64        implementing and solving arbitrary Measurement Equations

I don't understand why I have packages from KERN4 and 5 when I only have the PPA for KERN3 added to my system

**Comment by gijzelaerr** [comment]
KERN-3 contains
```
meqtrees-cattery 1.5.3 uploaded 2018-02-06
meqtrees-timba 1.5.0  uploaded 2017-11-07
kittens 1.3.3 uploaded 2017-11-15
```
KERN 4 was released 06 2018 and KERN 5 even later, so i'm not sure what makes you think there are KERN 4 and KERN 5 packages in KERN 3?


```

**Comment by gijzelaerr** [comment]
Ben,I guess you are misreading the version numbers. For example `1.5.0-1kern5` means there is a KERN specific revision of the package number 5 of software version 1.5.0. This is unrelated to the actual KERN version number.

**Comment by gijzelaerr** [comment]
So this is probably just a bug in that specific release?

**Comment by bennahugo** [comment]
oh ok thanks for explaining your versioning scheme. I always thought the last number is the kern version. Doesn't quite explain @bmerry's recent breakage, but maybe it is some unholy interaction from an upstream dependency that received a backport to 16.04 recently. That was already fixed in more recent releases of KERN.

**Comment by gijzelaerr** [comment]
If you look on the PPA page of KERN-3:

https://launchpad.net/~kernsuite/+archive/ubuntu/kern-3

you can see the last update was 21 weeks ago (casacore-data). This package should be updated every week with new data, but i lost my build machine by the ratt hack and didn't find the time to replace it yet.

The updates before that are unrelated or are +70 weeks ago.
