### ISSUE TITLE
Error using RandomPolc

### ISSUE THREAD

**Issue by TariqBlecher** [ska-sa/meqtrees-cattery#25]
Hi I'm trying to use turbo-sim to simulate rapidly varying atmosphere. The SINE ERROR option works fine but when I try the RandomPolc option I get this error..

tdlc(Compile.py:287:run_forest_definition): exception defining forest from TDL file: turbo-sim.py
Traceback (most recent call last):
  File "/usr/local/meqtrees/Timba/install/symlinked-release/libexec/python/Timba/TDL/Compile.py", line 224, in run_forest_definition
    define_func(ns,**args);
  File "turbo-sim.py", line 185, in _define_forest
    output = meqmaker.make_predict_tree(ns,uvdata=model_spigots);
  File "/usr/local/meqtrees/Cattery/Meow/TensorMeqMaker.py", line 267, in make_predict_tree
    return MeqMaker.make_predict_tree(self,ns,other_sources,uvdata=uvdata,ifrs=ifrs);
  File "/usr/local/meqtrees/Cattery/Meow/MeqMaker.py", line 998, in make_predict_tree
    Jj,solvable = self._get_jones_nodes(ns,jt,stations);
  File "/usr/local/meqtrees/Cattery/Meow/MeqMaker.py", line 765, in _get_jones_nodes
    inspectors=inspectors);
  File "/usr/local/meqtrees/Cattery/Siamese/OMS/oms_gain_models.py", line 48, in compute_jones
    gaingen(ns.xa,station=p);
TypeError: make_node() takes exactly 4 arguments (3 given)
Exception caught:
Traceback (most recent call last):
  File "/usr/local/meqtrees/Timba/install/symlinked-release/bin/meqtree-pipeliner.py", line 135, in <module>
    module,ns,msg = Compile.compile_file(mqs,script,config=section);
  File "/usr/local/meqtrees/Timba/install/symlinked-release/libexec/python/Timba/TDL/Compile.py", line 303, in compile_file
    predef_args=predef_args,define_args=define_args,postdef_args=postdef_args);
  File "/usr/local/meqtrees/Timba/install/symlinked-release/libexec/python/Timba/TDL/Compile.py", line 293, in run_forest_definition
    raise TDL.CumulativeError(*ns.GetErrors());
CumulativeError: 
 [  1] make_node() takes exactly 4 arguments (3 given)
### Stopping the meqserver
meqserver(meqserver.py:288:stop_default_mqs): meqserver not exited yet, waiting another 10 seconds
### All your batch are not belong to us, returning with error code
Command exited with non-zero status 1
0.67user 0.29system 0:11.42elapsed 8%CPU (0avgtext+0avgdata 117464maxresident)k
152inputs+32outputs (0major+54276minor)pagefaults 0swaps

**Comment by o-smirnov** [comment]
Should work now.
