### ISSUE TITLE
calico-stefcal.py astype error

### ISSUE THREAD

**Issue by IanHeywood** [ska-sa/meqtrees-cattery#28]
Related to me not using Stefcal as per https://github.com/ska-sa/meqtrees/issues/861, I get the following error. I just git pulled the devel branch so I should be up to date. And I've successfully run Stefcal in recent times so one of the various updates to my machine that happen behind the scenes might be to blame...

```
TypeError: astype() takes no keyword arguments
Traceback (most recent call last):
  File "/data/VELA_2/hey036/Software/meqtrees-cattery/Cattery/Calico/OMS/StefCal/StefCal.py", line 424, in get_result
    m0 = model0.setdefault(pq,[0,0,0,0])[num] = pad_array(m);
  File "/data/VELA_2/hey036/Software/meqtrees-cattery/Cattery/Calico/OMS/StefCal/StefCal.py", line 415, in pad_array
    return x.astype(get_dtype(dd),copy=True)
```

**Comment by o-smirnov** [comment]
No I think that's my recent change, coupled with you running an older numpy. What's your numpy version?

**Comment by IanHeywood** [comment]
1.6.2

**Comment by o-smirnov** [comment]
OK easy fix, see latest devel.

**Comment by IanHeywood** [comment]
I've updated but the problem perists, and there's a tile shape issue now that I don't think was there before. This is for both VLA and ASKAP Measurement Sets, both of which have worked fine in the past.

```
28.66 gainopts(GainOpts.py:215:load_initval): not loading G solutions: gain.cp does not exist
29.53 gainopts(StefCal.py:684:get_result): Solvable: 351 of 351 inteferometers (324 have valid data), with 26 solvable antennas
29.53 gainopts(GainOpts.py:297:init_solver): stefcal G solve=1 GainDiag, using 324 solvable inteferometers
29.53 gainopts(GainOpts.py:298:init_solver):   solution intervals: [4, 4] smoothing kernel: ()
tile_data exception, tiled_shape: [14, 4, 16, 4] , arg: (56, 64)
Traceback (most recent call last):
  File "/data/VELA_2/hey036/Software/meqtrees-cattery/Cattery/Calico/OMS/StefCal/StefCal.py", line 775, in get_result
    flagged |= self.run_gain_solution(opt,model,data,weight,bitflags,flag_null_gains=True,looptype=looptype);
  File "/data/VELA_2/hey036/Software/meqtrees-cattery/Cattery/Calico/OMS/StefCal/StefCal.py", line 1257, in run_gain_solution
    self.compute_chisq(model,data,gopt.solver,weight=weight,bitflags=bitflags);
  File "/data/VELA_2/hey036/Software/meqtrees-cattery/Cattery/Calico/OMS/StefCal/StefCal.py", line 1187, in compute_chisq
    res = gain.residual(model,data,pq);
  File "/data/VELA_2/hey036/Software/meqtrees-cattery/Cattery/Calico/OMS/StefCal/GainDiag.py", line 321, in residual
    corr = self.apply(lhs,pq,index=True,cache=cache,tiler=tiler);
  File "/data/VELA_2/hey036/Software/meqtrees-cattery/Cattery/Calico/OMS/StefCal/GainDiag.py", line 359, in apply
    for d,(i,j) in zip(lhs,IJ2x2) ];
  File "/data/VELA_2/hey036/Software/meqtrees-cattery/Cattery/Calico/OMS/StefCal/DataTiler.py", line 73, in tile_data
    return x.reshape(self.tiled_shape).astype(dtype or x.dtype,copy=False) if not (numpy.isscalar(x) or x.size == 1) else x;
TypeError: astype() takes no keyword arguments
```

**Comment by o-smirnov** [comment]
Um, sloppy. Another quick fix, please try again.

**Comment by o-smirnov** [comment]
Did I say sloppy? OK, this should do it.

Are you running it via pyxis, BTW?

**Comment by IanHeywood** [comment]
OK we're in business.

I'm running it via the browser at the moment. If I run Stefcal via Pyxis I always use the mqt.run method, I've never really gotten on with the stefcal.stefcal module.

Cheers.

**Comment by o-smirnov** [comment]
Cool. Check ratt-ru/calibration-pipelines if you want an example of using
stefcal.stefcal... but if mqt.run works for you, that's fine too.
