### ISSUE TITLE
MeerKAT beams raise exception in interpolator

### ISSUE THREAD

**Issue by bennahugo** [ska-sa/meqtrees-cattery#74]
Trying to apply MeerKAT beams (1.0~1.1ghz) on DEEP_2 subset. Raising the following error in the interpolation code:
```
 - 17:57:13 - AsyncProcessPool          | [io00] process io00: exception raised processing job DATA:0:0: Traceback (most recent call last):
  File "/ddfvenv/local/lib/python2.7/site-packages/DDFacet/Other/AsyncProcessPool.py", line 801, in _dispatch_job
    result = call(*args, **kwargs)
  File "/ddfvenv/local/lib/python2.7/site-packages/DDFacet/Data/ClassVisServer.py", line 536, in _handler_LoadVisChunk
    JonesMachine.InitDDESols(DATA)
  File "/ddfvenv/local/lib/python2.7/site-packages/DDFacet/Data/ClassJones.py", line 87, in InitDDESols
    DicoSols, TimeMapping, DicoClusterDirs = self.MakeSols("Beam", DATA, quiet=quiet)
  File "/ddfvenv/local/lib/python2.7/site-packages/DDFacet/Data/ClassJones.py", line 231, in MakeSols
    DicoSols = self.GiveBeam(DATA["uniq_times"], quiet=quiet)
  File "/ddfvenv/local/lib/python2.7/site-packages/DDFacet/Data/ClassJones.py", line 558, in GiveBeam
    DicoBeam = self.EstimateBeam(beam_times, RAs, DECs)
  File "/ddfvenv/local/lib/python2.7/site-packages/DDFacet/Data/ClassJones.py", line 601, in EstimateBeam
    Beam=self.GiveInstrumentBeam(ThisTime,RA,DEC)
  File "/ddfvenv/local/lib/python2.7/site-packages/DDFacet/Data/ClassFITSBeam.py", line 217, in evaluateBeam
    beamjones = [ self.vbs[i].interpolate(l,m,freq=self.freqs,freqaxis=1) for i in range(4) ]
  File "/ddfvenv/lib/python2.7/site-packages/Cattery/Siamese/OMS/InterpolatedBeams.py", line 335, in interpolate
    scale if numpy.isscalar(scale) else scale[above|below])
IndexError: boolean index did not match indexed array along dimension 0; dimension is 34391 but corresponding boolean dimension is 119
```

**Comment by ludwigschwardt** [comment]
That is a symptom of a new NumPy (1.18?) that has become quite strict on indexing and other stuff. Your boolean indices `above` and `below` better be the same length as `scale`. The fact that they are so different suggests some brokenness.

**Comment by bennahugo** [comment]
@ludwigschwardt same docker container is running with VLA FITS beams so I think it is likely something slightly more insidious, but good call will check which version of numpy is used here.

**Comment by bennahugo** [comment]
@SpheMakh discovered a workaround for this one: the data bandwidth has to lie strictly within the frequency extent of the beams: > freq_0 and < freq_N. If the data includes these limits or exceeds them we encounter the interpolation errors. For now I will just hammer the data into the correct shape. When we get the full LBand beams from Kahn this should not be a problem. Keeping the issue open because it is definitely a bug.

**Comment by o-smirnov** [comment]
Yeah looks like the code meant to address #32 is a little dodgy.

**Comment by bennahugo** [comment]
@o-smirnov just an update on this: getting nans in the dirty images when I try apply the beam - it appears to run through but then crashes because there is no PSF to fit.

**Comment by bennahugo** [comment]
confirm this is also a problem in master

**Comment by bennahugo** [comment]
@o-smirnov never mind this was stupidity at its best: the CRVAL{1,2} was given in pixels and the area beyond 3 degrees were set to nans.... working fine now
