### ISSUE TITLE
Batchtest fails

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/meqtrees-cattery#88]
```
========== Running makems                                                
('========== $', 'makems /code/test/Batchtest/WSRT_makems.cfg')          
('========== $', 'mv WSRT.MS_p0 WSRT.MS')                                
('========== $', 'pyxis WSRT.MS ms.prep')                                
Traceback (most recent call last):                                       
  File "batch_test.py", line 90, in <module>                             
    run("pyxis WSRT.MS ms.prep"); #TODO: this is hacky, bug in CASAcore  
  File "batch_test.py", line 28, in run                                  
    raise RuntimeError("failed with exit code %x"%code);                 
RuntimeError: failed with exit code 1                                    
```
```
λ  /usr/bin/addbitflagcol WSRT.MS                                            
creating new column BITFLAG_ROW using an IncrementalStMan storage manager    
DATA column storage manager type is StandardStMan                            
BITFLAG column will use a default storage manager                            
Adding BITFLAG column with fixed shape: [4, 64]                              
[1]    25531 segmentation fault (core dumped)  /usr/bin/addbitflagcol WSRT.MS
```

**Comment by bennahugo** [comment]
Cannot reproduce @gijzelaerr. Maybe it is a KERN specific issue when you built Timba

However you did break pyxis in places :)

**Comment by bennahugo** [comment]
Ok no... can't python3ize this codebase

Running python 2 only I run into this issue as well

**Comment by o-smirnov** [comment]
But how is it even a python issue when ``addbitflagcol`` fails? It's a binary compiled from C++ (and casacore)....

**Comment by bennahugo** [comment]
Yup - it is LOFAR's fault! I've given ska-sa/makems some TLC and it compiles on bionic with the latest casacore. Building it from source in the dockerfile of cattery fixes the issue. @gijzelaerr you will have to do the same for your dockerfiles, unless you feel like adding it back into KERN is a good use of your time.

```
Baseline 576m, 6 ifrs: 0-4 1-5 2-6 3-7 4-8 5-9
Baseline 720m, 5 ifrs: 0-5 1-6 2-7 3-8 4-9
Baseline 864m, 4 ifrs: 0-6 1-7 2-8 3-9
Baseline 1008m, 3 ifrs: 0-7 1-8 2-9
Baseline 1152m, 2 ifrs: 0-8 1-9
Baseline 1296m, 3 ifrs: 0-9 10-12 11-13
Baseline 1332m, 2 ifrs: 0-10 9-12
Baseline 1404m, 2 ifrs: 0-11 9-13
00:00:00: Closing MS.
========== Verifying residual image
WSRT.MS.CORRECTED_DATA.channel.1ch.fits and /code/test/Batchtest/test-refresidual.fits differ by 1.84272e-05, this is within tolerance
========== Break out the bubbly, this hog is airborne!
Bye!
```

**Comment by gijzelaerr** [comment]
I think we should replace makems with writems which is now bundled with casacore?
