### ISSUE TITLE
Batchtest fails for py3

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/meqtrees-cattery#89]
```
Created global VDS file WSRT.MS.gds
  File "/usr/local/bin/pyxis", line 156
    'OUTDIR','LOG','SPAWN_SCREEN_TITLE',
            ^
SyntaxError: invalid syntax
========== Removing files
========== $ rm -fr WSRT.MS* WSRT*img WSRT*fits
========== Running makems
========== $ makems /code/test/Batchtest/WSRT_makems.cfg
========== $ mv WSRT.MS_p0 WSRT.MS
========== $ pyxis WSRT.MS ms.prep
Traceback (most recent call last):
  File "batch_test.py", line 90, in <module>
    run("pyxis WSRT.MS ms.prep"); #TODO: this is hacky, bug in CASAcore
  File "batch_test.py", line 28, in run
    raise RuntimeError("failed with exit code %x"%code);
RuntimeError: failed with exit code 1
The command '/bin/sh -c python3 batch_test.py' returned a non-zero code: 1
```
the issue is pyxis not being py3 compatible:

https://github.com/ska-sa/pyxis/issues/88

**Comment by gijzelaerr** [comment]
this is solved per pyxis 1.6.0
